name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Сборка бинарника
        run: |
          echo "Ваша команда компиляции"
          # Например: gcc main.c -o my-app
          # Создайте артефакт, который хотите загрузить
          echo "demo" > my-app.exe

      - name: Загрузка в релиз
        uses: softprops/action-gh-release@v2
        with:
          files: |
            my-app.exe
            # Можно перечислить несколько файлов
            # LICENSE
            # archive.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}